config/routes.rb
Rails.application.routes.draw do
  root 'matriculas#index'
  resources :alunos
  resources :matriculas
  match 'matriculas/:id/pagar' => 'matriculas#pagar', controller: 'matriculas', action: 'pagar', via: :get
  match 'matriculas/:id' => 'matriculas#inativar', controller: 'matriculas', action: 'inativar', via: :post
  resources :cursos
  resources :qualificacaos

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/aluno.rb
class Aluno < ApplicationRecord
  has_many :matriculas
  validates_presence_of(:nome, message: " - deve ser preenchido")
  validates_presence_of(:cpf, message: " - deve ser preenchido")
  validates_length_of(:cpf, maximum: 11, message: " - deve conter 11 caracteres")
  validates_uniqueness_of(:cpf, message: " - já está cadastrado.")
  validates_numericality_of(:cpf, message: " - deve conter somente números")
  validate :validar_cpf

  validates_presence_of(:rg, message: " - deve ser preenchido")
  validates_presence_of(:data_nascimento, message: " - deve ser preenchido")
  
  private
  def validar_cpf
    nulos = %w{12345678909 11111111111 22222222222 33333333333 44444444444 55555555555 66666666666 77777777777 88888888888 99999999999 00000000000}
    errors.add(:cpf, " - deve ser válido ") if !Cpf.new(cpf).valido?||nulos.member?(cpf)
  end
end

app/controllers/alunos_controller.rb
class AlunosController < ApplicationController
  before_action :set_aluno, only: [:show, :edit, :update, :destroy]

  # GET /alunos
  # GET /alunos.json
  def index
    @alunos = Aluno.all
  end

  # GET /alunos/1
  # GET /alunos/1.json
  def show
  end

  # GET /alunos/new
  def new
    @aluno = Aluno.new
  end

  # GET /alunos/1/edit
  def edit
  end

  # POST /alunos
  # POST /alunos.json
  def create
    @aluno = Aluno.new(aluno_params)

    respond_to do |format|
      if @aluno.save
        format.html { redirect_to @aluno, notice: 'Aluno was successfully created.' }
        format.json { render :show, status: :created, location: @aluno }
      else
        format.html { render :new }
        format.json { render json: @aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alunos/1
  # PATCH/PUT /alunos/1.json
  def update
    respond_to do |format|
      if @aluno.update(aluno_params)
        format.html { redirect_to @aluno, notice: 'Aluno was successfully updated.' }
        format.json { render :show, status: :ok, location: @aluno }
      else
        format.html { render :edit }
        format.json { render json: @aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alunos/1
  # DELETE /alunos/1.json
  def destroy
    @aluno.destroy
    respond_to do |format|
      format.html { redirect_to alunos_url, notice: 'Aluno was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aluno
      @aluno = Aluno.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def aluno_params
      params.require(:aluno).permit(:cpf, :rg, :data_nascimento, :nome, :telefone)
    end
end

app/helpers/alunos_helper.rb
module AlunosHelper
end

app/views/alunos/_form.html.erb
<%= form_for(aluno) do |f| %>
  <% if aluno.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(aluno.errors.count, "erro") %> encontrado(s) ao salvar o registro:</h2>
      <ul>
      <% aluno.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %>
    <%= f.text_field :nome %>
  </div>

  <div class="field">
    <%= f.label :cpf %>
    <%= f.text_field :cpf %>
  </div>

  <div class="field">
    <%= f.label :rg %>
    <%= f.text_field :rg %>
  </div>

  <div class="field">
    <%= f.label :data_nascimento %>
    <%= f.date_select(:data_nascimento, order: [:day, :month, :year], start_year:Date.today.year-100) %>
  </div>

  <div class="field">
    <%= f.label :telefone %>
    <%= f.text_field :telefone %>
  </div>

  <div class="actions">
    <%= f.submit "Salvar" %>
  </div>
<% end %>

app/views/alunos/edit.html.erb
<h1>Editando Aluno</h1>

<%= render 'form', aluno: @aluno %>

<%= link_to 'Exibir', @aluno %> |
<%= link_to 'Voltar', alunos_path %>

app/views/alunos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Alunos</h1>

<table>
  <thead>
    <tr>
      <th>Cpf</th>
      <th>Rg</th>
      <th>Data nascimento</th>
      <th>Nome</th>
      <th>Telefone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @alunos.each do |aluno| %>
      <tr>
        <td><%= aluno.cpf %></td>
        <td><%= aluno.rg %></td>
        <td><%= aluno.data_nascimento %></td>
        <td><%= aluno.nome %></td>
        <td><%= aluno.telefone %></td>
        <td><%= link_to 'Exibir', aluno %></td>
        <td><%= link_to 'Editar', edit_aluno_path(aluno) %></td>
        <td><%= link_to 'Remover', aluno, method: :delete, data: { confirm: 'Confirma remoção?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo aluno', new_aluno_path %>

app/views/alunos/new.html.erb
<h1>Novo Aluno</h1>

<%= render 'form', aluno: @aluno %>

<%= link_to 'Voltar', alunos_path %>

app/views/alunos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @aluno.nome %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @aluno.cpf %>
</p>

<p>
  <strong>Rg:</strong>
  <%= @aluno.rg %>
</p>

<p>
  <strong>Data nascimento:</strong>
  <%= @aluno.data_nascimento %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @aluno.telefone %>
</p>

<%= link_to 'Editar', edit_aluno_path(@aluno) %> |
<%= link_to 'Voltar', alunos_path %>