config/routes.rb
Rails.application.routes.draw do
  root 'matriculas#index'
  resources :alunos
  resources :matriculas
  match 'matriculas/:id/pagar' => 'matriculas#pagar', controller: 'matriculas', action: 'pagar', via: :get
  match 'matriculas/:id' => 'matriculas#inativar', controller: 'matriculas', action: 'inativar', via: :post
  resources :cursos
  resources :qualificacaos

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/curso.rb
class Curso < ApplicationRecord
  has_many :matriculas
  validates_presence_of(:nome, message: " - deve ser preenchido")
  validates_presence_of(:valor_inscricao, message: " - deve ser preenchido")
  validates_numericality_of(:valor_inscricao, greater_than: 0, message: " - deve ser um valor maior que zero")
  validates_presence_of(:periodo, message: " - deve ser preenchido")
  validates_inclusion_of :periodo, :in => [1, 2, 3], message: " - deve ser 'Vespertino', 'Matutino' ou 'Integral'"

  def periodo_texto
    case periodo
    when 1 then
      return 'Vespertino'
    when 2 then
      return 'Matutino'
    when 3 then
      return 'Integral'
    end
  end
end

app/controllers/cursos_controller.rb
class CursosController < ApplicationController
  before_action :set_curso, only: [:show, :edit, :update, :destroy]

  # GET /cursos
  # GET /cursos.json
  def index
    @cursos = Curso.all
  end

  # GET /cursos/1
  # GET /cursos/1.json
  def show
  end

  # GET /cursos/new
  def new
    @curso = Curso.new
  end

  # GET /cursos/1/edit
  def edit
  end

  # POST /cursos
  # POST /cursos.json
  def create
    @curso = Curso.new(curso_params)

    respond_to do |format|
      if @curso.save
        format.html { redirect_to @curso, notice: 'Curso was successfully created.' }
        format.json { render :show, status: :created, location: @curso }
      else
        format.html { render :new }
        format.json { render json: @curso.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cursos/1
  # PATCH/PUT /cursos/1.json
  def update
    respond_to do |format|
      if @curso.update(curso_params)
        format.html { redirect_to @curso, notice: 'Curso was successfully updated.' }
        format.json { render :show, status: :ok, location: @curso }
      else
        format.html { render :edit }
        format.json { render json: @curso.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cursos/1
  # DELETE /cursos/1.json
  def destroy
    @curso.destroy
    respond_to do |format|
      format.html { redirect_to cursos_url, notice: 'Curso was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_curso
      @curso = Curso.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def curso_params
      params.require(:curso).permit(:nome, :valor_inscricao, :periodo)
    end
end

app/helpers/cursos_helper.rb
module CursosHelper
end

app/views/cursos/_form.html.erb
<%= form_for(curso) do |f| %>
  <% if curso.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(curso.errors.count, "erro") %> encontrado(s) ao salvar o registro:</h2>
      <ul>
      <% curso.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %>
    <%= f.text_field :nome %>
  </div>

  <div class="field">
    <%= f.label "R$ inscrição" %>
    <%= f.number_field :valor_inscricao, :step => 0.01, :value => (number_with_precision(f.object.valor_inscricao, :precision => 2) || 0.00)  %>
  </div>

  <div class="field">
    <%= f.label "Período" %>
    <%= f.select :periodo, options_for_select([["Matutino", "1"], ["Vespertino", "2"], ["Integral", "3"]])%>
  </div>

  <div class="actions">
    <%= f.submit "Salvar" %>
  </div>
<% end %>

app/views/cursos/edit.html.erb
<h1>Editando Curso</h1>

<%= render 'form', curso: @curso %>

<%= link_to 'Exibir', @curso %> |
<%= link_to 'Voltar', cursos_path %>

app/views/cursos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cursos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>R$ inscrição</th>
      <th>Período</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cursos.each do |curso| %>
      <tr>
        <td><%= curso.nome %></td>
        <td><%= curso.valor_inscricao %></td>
        <td><%= curso.periodo_texto %></td>
        <td><%= link_to 'Exibir', curso %></td>
        <td><%= link_to 'Editar', edit_curso_path(curso) %></td>
        <td><%= link_to 'Remover', curso, method: :delete, data: { confirm: 'Confirma remoção?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Curso', new_curso_path %>

app/views/cursos/new.html.erb
<h1>Novo Curso</h1>

<%= render 'form', curso: @curso %>

<%= link_to 'Voltar', cursos_path %>

app/views/cursos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @curso.nome %>
</p>

<p>
  <strong>R$ inscrição:</strong>
  <%= @curso.valor_inscricao %>
</p>

<p>
  <strong>Período:</strong>
  <%= @curso.periodo_texto %>
</p>

<%= link_to 'Editar', edit_curso_path(@curso) %> |
<%= link_to 'Voltar', cursos_path %>