config/routes.rb
Rails.application.routes.draw do
  root 'matriculas#index'
  resources :alunos
  resources :matriculas
  match 'matriculas/:id/pagar' => 'matriculas#pagar', controller: 'matriculas', action: 'pagar', via: :get
  match 'matriculas/:id' => 'matriculas#inativar', controller: 'matriculas', action: 'inativar', via: :post
  resources :cursos
  resources :qualificacaos

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/matricula.rb
class Matricula < ApplicationRecord
    belongs_to :aluno
    belongs_to :curso

    scope :ativos, -> {where(ativo: 'S')}

    validates_presence_of(:aluno_id, message: " - deve ser preenchido")
    validates_associated :aluno
    validates_presence_of(:curso_id, message: " - deve ser preenchido")
    validates_associated :curso
    validates_presence_of(:data_matricula, message: " - deve ser preenchido")
    validates_presence_of(:ano, message: " - deve ser preenchido")
    validates_numericality_of(:ano, greater_than: 0, message: " - deve ser um valor maior que zero")
    validates_numericality_of(:ano, greater_than_or_equal_to: Date.today.year, message: " - deve ser maior ou igual ao ano atual (#{Date.today.year})")
    validate :validar_unicidade_matricula

    private
    def validar_unicidade_matricula
      if ano != nil
        matriculas = Matricula.ativos.where("aluno_id = #{aluno_id} and ano = #{ano}")

        matriculas.each do |matricula|
          if curso.periodo==3||[curso.periodo, 3].include?(matricula.curso.periodo)
            errors.add(:curso_id, " - já existe uma matrícula para o curso de '#{matricula.curso.nome}' no mesmo período.")
            break
          end
        end
      end
    end
end

app/controllers/matriculas_controller.rb
class MatriculasController < ApplicationController
  before_action :set_matricula, only: [:show, :edit, :update, :destroy, :inativar, :pagar]

  def preparar_form
    @alunos = Aluno.order :nome
    @cursos = Curso.order :nome
  end
  # GET /matriculas
  # GET /matriculas.json
  def index
    @matriculas = Matricula.ativos
    @matriculas.includes(:aluno, :curso)
  end

  # GET /matriculas/1
  # GET /matriculas/1.json
  def show
  end

  # GET /matriculas/new
  def new
    @matricula = Matricula.new
    @matricula.ativo ||= 'S'
    @matricula.pago ||= 'N'
    @matricula.ano ||= Date.today.year
    preparar_form
  end

  # GET /matriculas/1/edit
  def edit
    preparar_form
  end

  # POST /matriculas
  # POST /matriculas.json
  def create
    @matricula = Matricula.new(matricula_params)

    respond_to do |format|
      if @matricula.save
        format.html { redirect_to @matricula, notice: 'Matrícula cadastrada com sucesso.' }
        format.json { render :show, status: :created, location: @matricula }
      else
        preparar_form
        format.html { render :new }
        format.json { render json: @matricula.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matriculas/1
  # PATCH/PUT /matriculas/1.json
  def update
    if params[:matricula] && params[:matricula][:valor_pago]
      pagamento(@matricula.id, params[:matricula][:valor_pago])
    else
      respond_to do |format|
        if @matricula.update(matricula_params)
          format.html { redirect_to @matricula, notice: 'Matrícula atualizada com sucesso.' }
          format.json { render :show, status: :ok, location: @matricula }
        else
          preparar_form
          format.html { render :edit }
          format.json { render json: @matricula.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /matriculas/1
  # DELETE /matriculas/1.json
  def destroy
    @matricula.destroy
    respond_to do |format|
      format.html { redirect_to matriculas_url, notice: 'Matrícula removida com sucesso.' }
      format.json { head :no_content }
    end
  end

  def inativar()
    @matricula.update_attribute(:ativo, 'N')
    @matricula.save
    respond_to do |format|
      format.html { redirect_to matriculas_url, notice: 'Matrícula inativada com sucesso.' }
      format.json { head :no_content }
    end
  end
  helper_method :inativar

  def pagar
    if @matricula.pago == "S"
      redirect_to matriculas_url, notice: 'Valor de inscrição já foi pago.'
    end
  end
  helper_method :pagar

  def pagamento(id, valorpago)
    matricula = Matricula.find(id)
    matricula.update_attribute(:pago, 'S')
    matricula.save
    caixa = Caixa.new
    caixa.valordivida = @matricula.curso.valor_inscricao
    caixa.valorpago = valorpago.to_f

    troco = []
    troco << "Troco: R$ #{caixa.calcula_valor_troco}"
    caixa.DefinirMelhorTroco do |qtde, tipo, nome|
      troco << "#{qtde}x #{tipo}(s) de #{nome} \n"
    end
    redirect_to matriculas_url, notice: "Pagamento efetuado com sucesso!" + troco.join("\n").html_safe
  end
  helper_method :pagamento

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_matricula
      @matricula = Matricula.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def matricula_params
      params.require(:matricula).permit(:data_matricula, :ano, :ativo, :pago, :aluno_id, :curso_id, :valor_pago)
    end
end

app/helpers/matriculas_helper.rb
module MatriculasHelper
end

app/views/matriculas/_form.html.erb
<%= form_for(matricula) do |f| %>
  <% if matricula.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(matricula.errors.count, "error") %> prohibited this matricula from being saved:</h2>

      <ul>
      <% matricula.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :data_matricula %>
    <%= f.date_select :data_matricula, order: [:day, :month, :year], start_year:Date.today.year %>
  </div>

  <div class="field">
    <%= f.label "Aluno" %>
    <%= f.collection_select(:aluno_id, @alunos, :id, :nome, :prompt => true) %>
  </div>

  <div class="field">
    <%= f.label "Curso" %>
    <%= f.collection_select(:curso_id, @cursos, :id, :nome, :prompt => true) %>
  </div>

  <div class="field">
    <%= f.label :ano %>
    <%= f.number_field :ano %>
  </div>

  <div class="field">
    <%= f.hidden_field :ativo %>
  </div>

  <div class="field">
    <%= f.hidden_field :pago %>
  </div>

  <div class="actions">
    <%= f.submit "Salvar" %>
  </div>
<% end %>

app/views/matriculas/edit.html.erb
<h1>Editando Matrícula</h1>

<%= render 'form', matricula: @matricula %>

<%= link_to 'Exibir', @matricula %> |
<%= link_to 'Voltar', matriculas_path %>

app/views/matriculas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Matrículas</h1>

<table>
  <thead>
    <tr>
      <th>Data</th>
      <th>Ano</th>
      <th>Aluno</th>
      <th>Curso</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @matriculas.each do |matricula| %>
      <tr>
        <td><%= matricula.data_matricula %></td>
        <td><%= matricula.ano %></td>
        <td><%= matricula.aluno.nome %></td>
        <td><%= matricula.curso.nome %></td>
        <td><%= link_to 'Exibir', matricula %></td>
        <td><%= link_to 'Editar', edit_matricula_path(matricula) %></td>
        <td><%= link_to 'Inativar', matricula, method: :inativar, data: { confirm: 'Confirma inativação?' } %></td>
        <td><%= link_to 'Pagar', "/matriculas/#{matricula.id}/pagar" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova matrícula', new_matricula_path %>

app/views/matriculas/new.html.erb
<h1>Nova Matrícula</h1>

<%= render 'form', matricula: @matricula %>

<%= link_to 'Voltar', matriculas_path %>

app/views/matriculas/pagar.html.erb
<h1> Pagamento de matrícula </h1>

<%= form_for(@matricula) do |f| %>
  <div class="field">
    <%= f.label "R$ pago" %>
    <%= f.number_field :valor_pago, :step => 0.01, :value => (number_with_precision(f.object.curso.valor_inscricao, :precision => 2) || 0.00)  %>
  </div>
  <div class="actions">
    <%= button_to "Pagar", f.object, method: :put %>
  </div>
<% end %>

app/views/matriculas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Data matrícula:</strong>
  <%= @matricula.data_matricula %>
</p>

<p>
  <strong>Ano:</strong>
  <%= @matricula.ano %>
</p>

<p>
  <strong>Aluno:</strong>
  <%= @matricula.aluno.nome %>
</p>

<p>
  <strong>Curso:</strong>
  <%= @matricula.curso.nome %>
</p>

<%= link_to 'Editar', edit_matricula_path(@matricula) %> |
<%= link_to 'Voltar', matriculas_path %>